"""Constants from the ControlCAN SDK."""

from __future__ import annotations

from pathlib import Path

from bms_can_monitor.config import resource_root

VCI_USBCAN1 = 3
VCI_USBCAN2 = 4
VCI_USBCAN2A = 4
VCI_USBCAN_E_U = 20
VCI_USBCAN_2E_U = 21

STATUS_ERR = 0
STATUS_OK = 1

CANALYST_II_DEVICE_TYPE = VCI_USBCAN2
DEFAULT_DEVICE_INDEX = 0
CAN_CHANNEL_1 = 0
CAN_CHANNEL_2 = 1

MODE_NORMAL = 0
MODE_LISTEN_ONLY = 1
MODE_SELF_TEST = 2

SEND_NORMAL = 0
SEND_SINGLE = 1

FRAME_DATA = 0
FRAME_REMOTE = 1

FRAME_STANDARD = 0
FRAME_EXTENDED = 1

STANDARD_ID_MASK = 0x7FF
EXTENDED_ID_MASK = 0x1FFFFFFF

PE_MACHINE_I386 = 0x014C
PE_MACHINE_AMD64 = 0x8664

PROJECT_ROOT = resource_root()
CONTROL_CAN_DIR = PROJECT_ROOT / "third_party" / "controlcan"
CONTROL_CAN_X64_DLL = CONTROL_CAN_DIR / "x64" / "ControlCAN.dll"
CONTROL_CAN_WIN32_DLL = CONTROL_CAN_DIR / "win32" / "ControlCAN.dll"
